Default: &defaults
  database: forkaholics.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: forkaholics_test.sqlite3
  <<: *defaults

Staging:
  database: forkaholics_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: forkaholics_production.sqlite3
  poolsize: 100
  <<: *defaults
